---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: test-dev
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:latest*
spec:
  releaseName: httpdev
  chart:
    git: ssh://git@github.com/mobichord/flux-get-started
    ref: dev
    path: charts/test-dev
  values:
    image:
      repository: darknode/httpbuddy
      tags: latest